runtime: python37
automatic_scaling: #Only applicable for appengine accounts with billing enabled
  max_instances: 1
  min_instances: 0

#instance_class: F2

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
  
- url: /compare
  script: auto
  secure: always
  redirect_http_response_code: 301
  
- url: /index
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /
  script: auto
  secure: always
  redirect_http_response_code: 301

